# Restricted Data {#restricteddata}

This section contains a list of datasets that are potentially useful for social scientists to analyze, but for which access is restricted. The focus here is not on small studies (e.g., randomized controlled trials for a small subset of the population), but on large datasets that can be of use to social scientists across disciplines.

Other than a description of the data (as far as possible), this section will also include information on how restrictions may be lifted (i.e., how to gain access), if possible. It is hoped that listing them here will promote transparency in data sharing across research teams, and eventually prevent wasteful overlap in primary data collection across institutions. As in the public data section, disaggregated data that can be used for research is the focus here. 

Readers who believe I have wrongly listed a dataset here (i.e., they are not restricted), or have more accurate information than provided, can contact me. Use the in-built annotation feature, or send me an email at <shannon.ang@ntu.edu.sg> if you know about a dataset that should be featured in this list but is not included here.

## Department of Statistics (DOS) Microdata {#dos}

The Singapore [Department of Statistics (DOS)](https://www.singstat.gov.sg){target="_blank"} regularly conducts a number of surveys that, if access to disaggregated data were provided, could advance Singapore social science greatly. These include the Household Expenditure Survey, the General Household Survey, as well as records from the Registry of Marriages to track marriage and divorce trends in Singapore. Disaggregated data (i.e., microdata) allow for deeper analysis than what is presented in the public domain - for instance, social scientists may examine age-period-cohort trends in marriage and divorce rather than be confined solely to period statistics (which may be misleading), or to decompose within- and between- group variance in household income/expenditures for a better understanding of inequality in Singapore.

Unfortunately, the DOS does not share disaggregated data with researchers. When asked, the chatbot on the DOS website states:

> The Department of Statistics (DOS) is unable to provide access to raw data or anonymised microdata in the public domain. You may wish to refer to our publications on the surveys conducted for the latest survey data. If the required aggregated data is not available in the reports, you could provide us with the table formats. Please send them to info@singstat.gov.sg. We will assess the availability of the data and, if customised and aggregated data generation is required, we will let you know the applicable cost-recovery fees.

Further, under section 7 of the [Statistics Act](https://sso.agc.gov.sg/Act/SA1973){target="_blank"}, "anonymised microdata" (i.e., disaggregated data) obtained using the powers of the Act (i.e., where individuals are legally compelled to provide information) can only be shared with other public agencies, or "any consultant commissioned by a public agency". This means that social scientists outside of the government can only access these data by being appointed as a consultant by a public agency, unless the Statistics Act is amended to include other classes of persons^[According to Section 7(2)(b)(ii), such classes may be specified in the Third Schedule.].

## NVPC Individual/Corporate Giving Study {#nvpc-igs}

The NVPC Individual/Corporate Giving Study is a biennial, repeated cross-section survey that has been conducted since 2000. Therefore, 10 waves of data from 2000-2018 are potentially available. Its key aim is to study trends in volunteerism and philantrophic giving over time. 

The study is administered by the National Volunteer and Philanthropy Centre (NVPC). Some details on the latest wave can be found at the NVPC website - <https://www.nvpc.org.sg/index.php?p=resources/individual-giving-study-2018-findings>. Melissa Kwee, the Chief Executive Officer of NVPC, has [publicly stated](https://www.todayonline.com/commentary/keeping-passion-alive-trying-change-world){target="_blank"} her desire for open data sharing, but it is unclear how to access data from the NVPC Individual/Corporate Giving Study, or how to contact the research team. There are no indications of plans to make the dataset publicly available.

## National Youth Survey (NYS) {#nys}

The NYS is a cross-sectional survey of youth in Singapore that is conducted every three to five years. Its goal is to understand the aspirations, challenges, and attitudes of young Singaporeans aged 15-34. The survey has been conducted five times thus far, in 2002, 2005, 2010, 2013 (N=2,843), and 2016 (N=3,531).

NYS is administered by the National Youth Council (NYC)'s research team. Details can be found at the NYC website - <https://www.nyc.gov.sg/en/initiatives/resources/national-youth-survey/>{target="_blank"} - which hosts illustrated PDF summaries of the survey findings from selected years. It does not list any plans to make the dataset publicly available.

## Retirement and Health Study (RHS) {#rhs}

The RHS is a longitudinal survey of Singapore residents’ retirement and healthcare needs and how they change over time. It is conducted by the Central Provident Fund Board (CPF). This is a panel study of individuals aged 45 to 85 in 2014, with the same individuals being interviewed once every two years (for ten years, beginning in 2014). The survey includes information on household expenses, employment, health, and financial status. This is a large study with potentially many uses - RHS purports to have reached out to more than 23,000 participants in the first two rounds of interviews^[<https://www.cpf.gov.sg/Assets/members/Documents/RHS_FAQ_Booklet.pdf>{target="_blank"}]. 

More information is available at <https://www.cpf.gov.sg/Members/Others/member-pages/retirement-and-health-study-(rhs)>{target="_blank"}. The RHS website does not list any plans to make the dataset publicly available, and is accessible only to government agencies or researchers working with/for government agencies. The RHS study team can be reached at <cpf_rhs@cpf.gov.sg>.

## Singapore Life Panel (SLP) {#slp}

The Singapore Life Panel administers an internet-based monthly survey to approximately 11,000 Singaporeans aged 50 to 70 years. Information on income, expenditure, health, work and housing choices are solicited from panel members. The panel survey is one of the largest population-representative monthly surveys conducted in the world. This study is unique in Singapore because of the monthly frequency of surveys - the sheer amount of data collected over time is unprecedented.

The Singapore Life Panel is housed at the [Centre for Research on the Economics of Ageing](https://crea.smu.edu.sg/singapore-monthly-panel){target="_blank"} at SMU. The SLP website does not list any plans to make the dataset publicly available outside of their own research team. The SLP team can be reached at <crea@smu.edu.sg>.

## Singapore Panel Study on Social Dynamics (SPSSD) {#spssd}

The Singapore Panel Study on Social Dynamics was started in 2014 to understand challenges related to family cohesion and functioning. It is a longitudinal panel study, starting with 5002 heads of households interviewed in 2014. Its purpose is to measure family dynamics, societal values and attitudes relevant to national identity and social mobility over time. Waves 1 to 4 of data collection have been completed^[See some basic descriptives here: https://lkyspp.nus.edu.sg/docs/default-source/ips/2018-07-11_spssd-wave2_english.pdf], with Wave 5 beginning in 2019. A strength of this study is its panel data - few Singapore datasets with rich data on family dynamics have this many waves collected from the same individuals over time.

The Principal Investigator for this study is Dr [Natalie Pang](https://lkyspp.nus.edu.sg/our-people/faculty/natalie-pang){target="_blank"} at the Institute of Policy Studies, NUS. The SPSSD website does not list any plans to make the dataset publicly available, probably because of restrictions imposed by government funders. The SPSSD study team can be reached at <ips.soclab@nus.edu.sg>.

## Youth Survey on Transitions and Evolving Pathways in Singapore (Youth STEPS)

Youth STEPS is a six-year longitudinal survey of Singaporean youth aged 17 to 24 that began in 2017 (N=4,041). It covers a wide range of topics, including respondents' educational and career trajectories, family relationships, civic participation, and attitudes regarding social mobility, family, marriage, and more. The survey is in its third wave (as of 2019) and is scheduled to be completed in 2022.

Youth STEPS is funded by the National Youth Council and administered by the Institute of Policy Studies (Social Lab), part of the Lee Kuan Yew School of Public Policy. The Principal Investigator is Dr [Leong Chan-Hoong](http://lkyspp.splashinteractive.sg/ips/about-us/staff-directory/leong-chan-hoong){target="_blank"}. The website does not list plans to make the data publicly available. Questions can be directed to <ips.soclab@nus.edu.sg>. 




